name: Publish Builder Image

on:
  push:
    branches:
      - main

# on:
#   release:
#     types:
#     - published

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Global Pack
        uses: buildpacks/github-actions/setup-pack@main
        with:
          pack-version: 0.20.0

      - name: Create Builder Image
        run: |
          pack create-builder builder --config builder.toml

      - name: Push Image
        run: |
          docker push ghcr.io/railwayapp/railway-builder:latest
