name: Publish Builder Image

on:
  push:
    branches:
      - main

# on:
#   release:
#     types:
#     - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Global Pack
        uses: buildpacks/github-actions/setup-pack@main
        with:
          pack-version: 0.20.0

      - name: Create Builder Image
        run: |
          pack create-builder railway-builder --config builder.toml

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push Image
        run: |
          docker push ghcr.io/railwayapp/railway-builder:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
