name: Publish Builder Image

on:
  push:
    branches:
      - main

# on:
#   release:
#     types:
#     - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Global Pack
        uses: buildpacks/github-actions/setup-pack@main
        with:
          pack-version: 0.20.0

      - name: Create Builder Image
        run: |
          pack create-builder railway-builder --config builder.toml

      - name: Tag Image
        run: |
          docker tag railway-builder ghcr.io/railwayapp/railway-builder:latest

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
